version: "3.9"

services:
  database:
    image: postgres
    container_name: database_serasaapp
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=serasa
      - POSTGRES_PASSWORD=Ser@sa01
      - POSTGRES_DB=serasaapp
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: serasaapp
    restart: always
    ports:
      - 3434:3434
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
