version: "3.9"

services:
  database:
    image: postgres
    container_name: database_parafuzzo
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=Roberto
      - POSTGRES_PASSWORD=Robert0
      - POSTGRES_DB=parafuzoapp
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: parafuzoapp
    restart: always
    ports:
      - 3535:3535
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
