version: "3.9"

services:
  database:
    image: postgres
    container_name: database_serasaapp
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=Roberto
      - POSTGRES_PASSWORD=Robert0
      - POSTGRES_DB=parafuzoapp
    volumes:
      - pgdata:/data/postgres

  # app:
  #   build: .
  #   container_name: parafuzoapp
  #   restart: always
  #   ports:
  #     - 3001:3001
  #     - 9229:9229
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local
